---
title: "Graphic Outputs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```
##### Insights into US Bikeshare Companies 

```{r libraries, include=FALSE}
library(ggplot2)
library(tidyr)
```

##### Q1. 2017-2019 Monthly Trip Counts from Divvybikes and Bluebikes

```{r q1-biketrips, include=FALSE}
q1 <- read.csv("https://raw.githubusercontent.com/cheryltky/bikeshare_studies/main/csvdata/Q1.csv", sep=",", header = T)
head(q1)
str(q1)
#add index to dataframe, remove NAs
q1$index <- seq_len(dim(q1)[1])
q1 <-na.omit(q1)
q1
```


```{r divvy-blue, echo = FALSE}

plot(q1$index, q1$trips_bluebike, pch=20, col="blue", bty='n', xaxt='n', xlab='', ylab="Number of Trips", ylim=c(min(c(q1$trips_bluebike, q1$trips_divvy)), max(c(q1$trips_bluebike, q1$trips_divvy))))
points(q1$trips_divvy, pch=20, col='red')
axis(1, at=q1$index, labels=q1$month_year, las=2)
lines(q1$index, q1$trips_bluebike, col="blue", lwd=1)
lines(q1$index, q1$trips_divvy, col="red", lwd=1)

```



```{r ggplot method, include=FALSE}
dat <- read.csv("https://raw.githubusercontent.com/cheryltky/bikeshare_studies/main/csvdata/Q1.csv", sep=",", header = T)

dat$index <- seq_len(dim(dat)[1])
datl <- gather(dat, company, number_of_trips, trips_bluebike:trips_divvy)

datl

ggplot(datl, aes(x=index, y=number_of_trips, color=as.factor(company))) + geom_point() + scale_x_continuous(breaks=dat$index, labels=dat$month_year) + theme(axis.text.x = element_text(angle=90)) + xlab("Date") + ylab("Number of Trips") + geom_line(data = datl, aes(x=index, y=number_of_trips))

geom_smooth(method="loess")
```

##### Q2. Subscription User Counts
```{r subscriptions, echo=FALSE}

```



##### Q3. Seasonal Vs Daily Commuter Trends
##### Q4. Total Trips
##### Q5. Total Trips
##### Q6. Total Trips
##### Q7. Total Trips

